{% set version = '1.1.6' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dashboardthemes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dashboardthemes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dashboardthemes/dashboardthemes_{{ version }}.tar.gz
  sha256: cc80bcd4b66d2418fe08636a25425083574d406e4bd9dfa8d170663aeb23717a

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools >=0.3.5
  run:
    - r-base
    - r-htmltools >=0.3.5

test:
  commands:
    - $R -e "library('dashboardthemes')"           # [not win]
    - "\"%R%\" -e \"library('dashboardthemes')\""  # [win]

about:
  home: https://github.com/nik01010/dashboardthemes
  license: MIT
  summary: Allows manual creation of themes and logos to be used in applications created using
    the 'shinydashboard' package. Removes the need to change the underlying css code
    by wrapping it into a set of convenient R functions.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: dashboardthemes
# Type: Package
# Title: Customise the Appearance of 'shinydashboard' Applications using Themes
# Version: 1.1.6
# Authors@R: person("Nik", "Lilovski", email = "nik.lilovski@outlook.com", role = c("aut", "cre"))
# Maintainer: Nik Lilovski <nik.lilovski@outlook.com>
# Description: Allows manual creation of themes and logos to be used in applications created using the 'shinydashboard' package. Removes the need to change the underlying css code by wrapping it into a set of convenient R functions.
# URL: https://github.com/nik01010/dashboardthemes
# BugReports: https://github.com/nik01010/dashboardthemes/issues
# Depends: R (>= 3.2.3)
# Imports: htmltools (>= 0.3.5)
# Suggests: testthat, lintr, knitr, rmarkdown, glue, covr
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.0
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2022-07-13 17:57:45 UTC; Nik
# Author: Nik Lilovski [aut, cre]
# Repository: CRAN
# Date/Publication: 2022-07-13 18:20:02 UTC
